version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_URI=redis://redis:6379/0
    depends_on:
      - redis
